#!/bin/bash

#var colours
red='\033[1;31m'
green='\033[1;32m'
blue='\033[1;36m'
yellow='\033[1;33m'

#coding section
ip=`curl -s ifconfig.me`
banner=`figlet -f slant 'Public Ip'`
clear
echo -e "${red}$banner"
echo -e "${green}[+]${blue}Your Public IP is: ${yellow}$ip"
